name: PR Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: .github/workflows/subworkflow-build.yml
    secrets: inherit

  deploy:
    uses: .github/workflows/subworkflow-deploy.yml
    secrets: inherit
    if: github.actor != 'dependabot[bot]'
    needs: [build]
