name: PR Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/subworkflow-build.yml
    secrets: inherit
    permissions:
      contents: read

  deploy:
    uses: ./.github/workflows/subworkflow-deploy.yml
    secrets: inherit
    if: github.actor != 'dependabot[bot]'
    needs: [build]
    permissions:
      contents: read
      pull-requests: write
