name: "Release to App Marketplace"

on:
  workflow_call:
    inputs:
      ref:
        type: string
        description: "The commit ref to build"
        default: ${{ github.ref }}
        required: false

    secrets:
      APP_REGISTRY_KEY: { required: true }

jobs:
  release:
    name: Release App
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:

      - name: Register release with apps registry
        id: register_with_apps_registry
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "x-api-key: ${{ secrets.APP_REGISTRY_KEY }}" \
            -d '{"repositoryUrl": "'${{ github.server_url }}/${{ github.repository }}', "type": "github""}' \
            https://apps.deskpro-service.com/register

      - name: Trigger release
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "x-api-key: ${{ secrets.APP_REGISTRY_KEY }}" \
            -d '{"repositoryUrl": "'${{ github.server_url }}/${{ github.repository }}'"}' \
            https://apps.deskpro-service.com/release